'use client';

import * as React from 'react';
import { X, Sparkles, MessageSquarePlus } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { useAiSummary } from '@/lib/hooks/use-mail';
import { useUIStore } from '@/store/ui-store';

interface AiSummaryPanelProps {
  threadId: string;
  onDraftReply: () => void;
}

/**
 * Inline AI Summary card, rendered above the email thread when toggled on.
 * Previously a fixed slide-in aside on the right; moved inline per user
 * preference so the summary sits directly above the message content.
 */
export function AiSummaryPanel({ threadId, onDraftReply }: AiSummaryPanelProps) {
  const { aiPanelOpen, setAiPanelOpen } = useUIStore();
  const { data: summary, isLoading } = useAiSummary(threadId);

  return (
    <AnimatePresence initial={false}>
      {aiPanelOpen && (
        <motion.section
          key="ai-summary-inline"
          initial={{ opacity: 0, height: 0, y: -8 }}
          animate={{ opacity: 1, height: 'auto', y: 0 }}
          exit={{ opacity: 0, height: 0, y: -8 }}
          transition={{ type: 'tween', duration: 0.2, ease: 'easeOut' }}
          className="mb-4 overflow-hidden"
          aria-label="AI Summary"
        >
          <div className="rounded-xl border border-primary-200 bg-primary-50/50 p-4 dark:border-primary-900/50 dark:bg-primary-950/20">
            {/* Header */}
            <div className="mb-3 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary-100 dark:bg-primary-900/40">
                  <Sparkles size={14} className="text-primary-600 dark:text-primary-400" />
                </div>
                <h2 className="text-sm font-semibold text-gray-900 dark:text-gray-100">
                  AI Summary
                </h2>
              </div>
              <button
                onClick={() => setAiPanelOpen(false)}
                className="flex h-7 w-7 items-center justify-center rounded-lg text-gray-400 transition-colors hover:bg-gray-100 dark:hover:bg-gray-800"
                aria-label="Close AI summary"
              >
                <X size={14} />
              </button>
            </div>

            {/* Content */}
            <div className="space-y-3">
              {isLoading || !summary ? (
                <div className="space-y-2">
                  <Skeleton className="h-4 w-3/4" />
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-5/6" />
                </div>
              ) : (
                <>
                  <p className="text-sm leading-relaxed text-gray-700 dark:text-gray-300">
                    {summary.summary}
                  </p>

                  {summary.keyPoints.length > 0 && (
                    <div>
                      <h3 className="mb-1.5 text-xs font-semibold uppercase tracking-wider text-gray-400">
                        Key Points
                      </h3>
                      <ul className="space-y-1">
                        {summary.keyPoints.map((point, i) => (
                          <li
                            key={i}
                            className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300"
                          >
                            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary-500" />
                            {point}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {summary.urgencyReason && (
                    <div className="rounded-lg border border-red-200 bg-red-50 p-3 dark:border-red-900 dark:bg-red-950/30">
                      <p className="mb-1 text-xs font-semibold text-red-700 dark:text-red-400">
                        Why this is urgent
                      </p>
                      <p className="text-xs text-red-600 dark:text-red-400">
                        {summary.urgencyReason}
                      </p>
                    </div>
                  )}
                </>
              )}
            </div>

            {/* Footer */}
            <div className="mt-4 flex items-center justify-between gap-3 border-t border-primary-200/60 pt-3 dark:border-primary-900/40">
              <p className="text-[10px] text-gray-400 dark:text-gray-500">
                Generated by <span className="font-medium">Takshashila LLM</span>
                {summary && <> · {summary.retrievedChunkCount} context chunks</>}
              </p>
              <Button size="sm" onClick={onDraftReply} disabled={isLoading || !summary}>
                <MessageSquarePlus size={14} />
                Draft Reply
              </Button>
            </div>
          </div>
        </motion.section>
      )}
    </AnimatePresence>
  );
}
