"""Initial schema — create all tables from SQLAlchemy metadata.

This migration uses `op.create_all` via the ORM metadata. For production, you'd
replace this with explicit `op.create_table` calls autogenerated by Alembic.
"""
from alembic import op

from app.core.database import Base
import app.domain.models  # noqa: F401  (register models on metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
